'use strict';
const numbers = [2, 4, 42, 26, 7, 2, 58, 68, 19];
console.log('Before the loop.');
let i = 0;                              // Initialize counter variable.
while(i < numbers.length) {             // Iterate over ...
  const number = numbers[i];            // ... the number array.
  if (number % 2 === 1) {               // If a number is odd ...
    console.log('Odd number found.');   // ... output message ...
    break;                              // ... and abort the loop.
  } // Otherwise ...
  console.log(number);                  // ... output the number ...
  i++;                                  // ... and increment the counter variable.
}
console.log('After the loop.');