'use strict';
let result = 4;
result += 10;       // The variable now has the value 14 ...
result -= 2;        // ... now has the value 12 ...
result /= 3;        // ... now has the value 4 ...
result *= 5;        // ... now the value 20 ...
result %= 5;        // ... and now the value 0.